# Generated by Django 3.0.7 on 2021-03-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_wfxtransaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wfxtransaction',
            old_name='session_id',
            new_name='session',
        ),
    ]
