# Generated by Django 3.0.7 on 2021-03-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BalancesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_befor', models.FloatField()),
                ('balance_after', models.FloatField()),
                ('action_type', models.IntegerField(default=1)),
                ('source_from', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.IntegerField(default=1)),
                ('txn_id', models.CharField(max_length=255)),
                ('timeout', models.DecimalField(decimal_places=18, max_digits=65)),
                ('currency1_amount', models.FloatField()),
                ('currency2_amount', models.FloatField()),
                ('network_fee', models.FloatField()),
                ('currency1', models.CharField(max_length=255)),
                ('currency2', models.CharField(max_length=255)),
                ('checkout_url', models.CharField(max_length=1000)),
                ('status_url', models.CharField(max_length=1000)),
                ('qrcode_url', models.CharField(max_length=1000)),
                ('status', models.IntegerField()),
                ('status_text', models.CharField(max_length=255)),
                ('payment_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_text', models.CharField(max_length=255)),
                ('coin_syntax', models.CharField(max_length=10)),
                ('coin_name', models.CharField(max_length=40)),
            ],
        ),
    ]
